#!/bin/bash
STRING="WELCOME TO run_prog_100!"
echo $STRING


python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py
python MLDigits1_4.py

